<div align="center">
  <h1> 30 GÃ¼nde Python: 15. GÃ¼n - Python'da Hatalar </h1>
  <a class="header-badge" target="_blank" href="https://www.linkedin.com/in/asabeneh/">
  <img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social">
  </a>
  <a class="header-badge" target="_blank" href="https://twitter.com/Asabeneh">
  <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/asabeneh?style=social">
  </a>

  <sub>Yazar:
  <a href="https://www.linkedin.com/in/asabeneh/" target="_blank">Asabeneh Yetayeh</a><br>
  <small> Second Edition: Temmuz, 2021</small>
  </sub>
</div>
</div>

[<< 14. GÃ¼n](../14_Day_Higher_order_functions/14_higher_order_functions.md) | [16. GÃ¼n >>](../16_Day_Python_date_time/16_python_datetime.md)

![30DaysOfPython](../images/30DaysOfPython_banner3@2x.png)
- [ðŸ“˜ 15. GÃ¼n](#-day-15)
  - [Python'da Hatalar](#python-error-types)
    - [SÃ¶zdizimi HatasÄ±(SyntaxError)](#syntaxerror)
    - [Ä°sim HatasÄ±(NameError)](#nameerror)
    - [Ä°ndeks HatasÄ±(IndexError)](#indexerror)
    - [ModuleNotFoundError](#modulenotfounderror)
    - [AttributeError](#attributeerror)
    - [KeyError](#keyerror)
    - [Veri Tipi HatasÄ±(TypeError)](#typeerror)
    - [ImportError](#importerror)
    - [DeÄŸer HatasÄ±(ValueError)](#valueerror)
    - [SÄ±fÄ±ra BÃ¶lme HatasÄ±(ZeroDivisionError)](#zerodivisionerror)
  - [ðŸ’» AlÄ±ÅŸtÄ±rmalar: 15. GÃ¼n](#-exercises-day-15)

# ðŸ“˜ 15. GÃ¼n

## Python'da Hatalar

Kod yazarken, yazÄ±m hatasÄ± (typo) veya diÄŸer yaygÄ±n hatalarÄ± yapmak sÄ±kÃ§a gÃ¶rÃ¼lÃ¼r. EÄŸer kodumuz Ã§alÄ±ÅŸmazsa, Python yorumlayÄ±cÄ±sÄ± bir mesaj gÃ¶sterir; bu mesajda sorunun nerede meydana geldiÄŸi ve hata tÃ¼rÃ¼ hakkÄ±nda bilgi bulunur. Bazen ayrÄ±ca olasÄ± bir Ã§Ã¶zÃ¼m Ã¶nerisi de verir. Programlama dillerindeki farklÄ± hata tÃ¼rlerini anlamak, kodumuzu hÄ±zlÄ±ca hata ayÄ±klamamÄ±za yardÄ±mcÄ± olur ve yaptÄ±ÄŸÄ±mÄ±z iÅŸte daha iyi olmamÄ±zÄ± saÄŸlar.

Åžimdi en yaygÄ±n hata tÃ¼rlerini teker teker inceleyelim. Ã–ncelikle Python interactive shelli aÃ§alÄ±m. BilgisayarÄ±nÄ±n terminaline git ve python yaz. Python interactive shell aÃ§Ä±lacaktÄ±r.

### SÃ¶zdizimi HatasÄ±(SyntaxError)

**Ã–rnek 1: SyntaxError**

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'hello world'
  File "<stdin>", line 1
    print 'hello world'
                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello world')?
>>>
```

GÃ¶rdÃ¼ÄŸÃ¼n gibi bir _syntaxError_ dÃ¶ndÃ¼ Ã§Ã¼nkÃ¼ parantezi kapamayÄ± unuttuk ve Python hemen Ã§Ã¶zÃ¼m Ã¶nerisini sundu. HatayÄ± dÃ¼zeltelim.

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'hello world'
  File "<stdin>", line 1
    print 'hello world'
                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello world')?
>>> print('hello world')
hello world
>>>
```

Bu bir _SyntaxError'dÄ±_. DÃ¼zeltmeden sonra kodumuz sorunsuz bir ÅŸekilde Ã§alÄ±ÅŸtÄ±. Åžimdi diÄŸer hata tÃ¼rlerine bakalÄ±m.

### Ä°sim HatasÄ±(NameError)

**Ã–rnek 1: NameError**

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(age)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'age' is not defined
>>>
```

YukarÄ±daki mesajdan da gÃ¶rebileceÄŸin gibi, age isimli deÄŸiÅŸken tanÄ±mlÄ± deÄŸil. Evet, bir age deÄŸiÅŸkeni tanÄ±mlamamÄ±ÅŸtÄ±k ama sanki tanÄ±mlamÄ±ÅŸÄ±z gibi yazdÄ±rmaya Ã§alÄ±ÅŸÄ±yorduk. Åžimdi bunu, deÄŸiÅŸkeni tanÄ±mlayÄ±p bir deÄŸer atayarak dÃ¼zelteceÄŸiz.

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(age)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'age' is not defined
>>> age = 25
>>> print(age)
25
>>>
```

Hata tÃ¼rÃ¼ ise _NameError_ idi. HatanÄ±n ayÄ±klamasÄ±nÄ±, deÄŸiÅŸken adÄ±nÄ± tanÄ±mlayarak yaptÄ±k.

### Ä°ndeks HatasÄ±(IndexError)

**Ã–rnek 1: IndexError**

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> numbers = [1, 2, 3, 4, 5]
>>> numbers[5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>>
```

YukarÄ±daki Ã¶rnekte, Python bir _IndexError_ verdi Ã§Ã¼nkÃ¼ listenin yalnÄ±zca 0â€™dan 4â€™e kadar indeksleri vardÄ±, yani sÄ±nÄ±rlarÄ±n dÄ±ÅŸÄ±ndaydÄ±.

### ModuleNotFoundError

**Ã–rnek 1: ModuleNotFoundError**

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import maths
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'maths'
>>>
```

YukarÄ±daki Ã¶rnekte, kasÄ±tlÄ± olarak mathâ€™e fazladan bir s ekledim ve bu nedenle _ModuleNotFoundError_ oluÅŸtu. Fazladan sâ€™yi kaldÄ±rarak bunu dÃ¼zeltebiliriz.

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import maths
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'maths'
>>> import math
>>>
```

DÃ¼zeltmeyi yaptÄ±k, ÅŸimdi math modÃ¼lÃ¼ndeki bazÄ± fonksiyonlarÄ± kullanabiliriz.

### AttributeError

**Ã–rnek 1: AttributeError**

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import maths
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'maths'
>>> import math
>>> math.PI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'math' has no attribute 'PI'
>>>
```

GÃ¶rdÃ¼ÄŸÃ¼n gibi, yine bir hata yaptÄ±m! pi yerine maths modÃ¼lÃ¼nden bir PI fonksiyonunu Ã§aÄŸÄ±rmaya Ã§alÄ±ÅŸtÄ±m. Bu bir _AttributeErrorâ€™a_ yol aÃ§tÄ±, yani modÃ¼lde bÃ¶yle bir fonksiyon yok. Bunu PIâ€™yi pi ile deÄŸiÅŸtirerek dÃ¼zeltebiliriz.

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import maths
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'maths'
>>> import math
>>> math.PI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'math' has no attribute 'PI'
>>> math.pi
3.141592653589793
>>>
```

math modÃ¼lÃ¼nden pi'yi Ã§aÄŸÄ±rdÄ±k ve sonucu aldÄ±k.

### KeyError

**Ã–rnek 1: KeyError**

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> users = {'name':'Asab', 'age':250, 'country':'Finland'}
>>> users['name']
'Asab'
>>> users['county']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'county'
>>>
```

GÃ¶rdÃ¼ÄŸÃ¼n gibi, dictionary valuesini almak iÃ§in kullanÄ±lan keyin yazÄ±mÄ±nda bir hata vardÄ±. Bu bir _KeyErrorâ€™dÄ±r_ ve Ã§Ã¶zÃ¼mÃ¼ oldukÃ§a basittir. Hadi bunu dÃ¼zeltelim!

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> user = {'name':'Asab', 'age':250, 'country':'Finland'}
>>> user['name']
'Asab'
>>> user['county']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'county'
>>> user['country']
'Finland'
>>>
```

HatayÄ± debug ettik, kodumuz Ã§alÄ±ÅŸtÄ± ve Ã§Ä±ktÄ±mÄ±zÄ± aldÄ±k.

### Veri Tipi HatasÄ±(TypeError)

**Ã–rnek 1: TypeError**

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 4 + '3'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>>
```

YukarÄ±daki Ã¶rnekte bir _TypeError_ dÃ¶ndÃ¼ Ã§Ã¼nkÃ¼ bir sayÄ±ya string ekleyemeyiz. Ä°lk Ã§Ã¶zÃ¼m, stringâ€™i int veya floatâ€™a dÃ¶nÃ¼ÅŸtÃ¼rmek olur. Bir diÄŸer Ã§Ã¶zÃ¼m ise sayÄ±yÄ± stringâ€™e Ã§evirmektir (sonuÃ§ bu durumda '43' olur). Åžimdi sorunu Ã§Ã¶zelim.

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 4 + '3'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> 4 + int('3')
7
>>> 4 + float('3')
7.0
>>>
```

Hata ortadan kaldÄ±rÄ±ldÄ± ve beklediÄŸimiz sonucu elde ettik.

### ImportError

**Ã–rnek 1: ImportError**

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from math import power
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'power' from 'math'
>>>
```

Math modÃ¼lÃ¼nde power adlÄ± bir fonksiyon yok. DoÄŸrusu _pow_. DÃ¼zeltilmiÅŸ hali:

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from math import power
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'power' from 'math'
>>> from math import pow
>>> pow(2,3)
8.0
>>>
```

### DeÄŸer HatasÄ±(ValueError)

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> int('12a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '12a'
>>>
```

Bu durumda, verilen stringâ€™i bir sayÄ±ya dÃ¶nÃ¼ÅŸtÃ¼remeyiz Ã§Ã¼nkÃ¼ iÃ§inde 'a' harfi bulunuyor.

### SÄ±fÄ±ra BÃ¶lme HatasÄ±(ZeroDivisionError)

```py
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 1/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>>
```

Bir sayÄ±yÄ± sÄ±fÄ±ra bÃ¶lemeyiz.

Python hata tÃ¼rlerinden bazÄ±larÄ±nÄ± iÅŸledik. EÄŸer daha fazlasÄ±nÄ± Ã¶ÄŸrenmek istiyorsanÄ±z Python dokÃ¼mantasyonundan Python hatalarÄ±nÄ± inceleyin. 
Hata tÃ¼rlerini okumada iyiysen, aynÄ± zamanda iyi bir programcÄ± olacaksÄ±n.

ðŸŒ• Ã‡ok iyi ilerliyorsunuz. Challenge'Ä±n 15. gÃ¼nÃ¼nÃ¼ tamamladÄ±nÄ±z ve baÅŸarÄ±ya giden yolun yarÄ±sÄ±nÄ± tamamladÄ±nÄ±z.You made it to half way to your way to greatness. Åžimdi beynin ve kaslarÄ±n iÃ§in biraz alÄ±ÅŸtÄ±rma yapalÄ±m.

## ðŸ’» AlÄ±ÅŸtÄ±rmalar: 15. GÃ¼n

1. Python interactive shell'inizi aÃ§Ä±n ve bu bÃ¶lÃ¼mde iÅŸlenen tÃ¼m hatalarÄ± deneyin.

ðŸŽ‰ TEBRÄ°KLER ! ðŸŽ‰

[<< 14. GÃ¼n](../14_Day_Higher_order_functions/14_higher_order_functions.md) | [16. GÃ¼n >>](../16_Day_Python_date_time/16_python_datetime.md)
